# Generated by Django 2.1.7 on 2019-05-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0007_auto_20190520_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
    ]
