# Generated by Django 2.1.7 on 2019-05-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0008_remove_curso_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
