# Generated by Django 2.1.7 on 2019-05-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0010_auto_20190520_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='semestre1',
            new_name='semestres',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='semestre2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='semestre3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='semestre4',
        ),
    ]
